name: GraalVM Check

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
    inputs:
      ballerina_version:
        description: 'Ballerina version'
        required: true
        default: '2201.11.0'

env:
  BALLERINA_DISTRIBUTION_VERSION: 2201.11.0   # Update this with the latest Ballerina version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21.0.3'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GraalVM installation
        run: |
          echo "GRAALVM_HOME: ${{ env.GRAALVM_HOME }}"
          echo "JAVA_HOME: ${{ env.JAVA_HOME }}"
          native-image --version
      - name: Set up Ballerina
        if: github.event_name == 'workflow_dispatch'
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ github.event.inputs.ballerina_version }}
      - name: Set up Ballerina
        if: github.event_name == 'schedule'
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BALLERINA_DISTRIBUTION_VERSION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: |
          ./gradlew build
      - name: Update dependency versions
        run: ./gradlew :jaeger-extension-ballerina:updateTomlVerions
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
      - name: Run Ballerina build using the native executable
        run: bal build --native ./ballerina
      - name: Run Ballerina tests using the native executable
        run: bal test --native ./ballerina
